# Generated by Django 3.2.7 on 2021-12-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='creat_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
