# Generated by Django 3.2.7 on 2021-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_new_news_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
