# Generated by Django 4.0 on 2021-12-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='images')),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
