# Generated by Django 4.0 on 2021-12-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lessons_name',
            new_name='lesson_name',
        ),
    ]
