# Generated by Django 4.0 on 2021-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_rename_lessons_name_lesson_lesson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='zvanie',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
