# Generated by Django 4.0 on 2021-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_teacher_zvanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
