# Generated by Django 4.0 on 2021-12-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_alter_teacher_zvanie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='zvanie',
        ),
    ]
