# Generated by Django 4.0 on 2021-12-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_remove_teacher_zvanie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
    ]
