# Generated by Django 4.0 on 2021-12-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_remove_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lesson_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lesson_num',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lesson_pdf',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
