# Generated by Django 4.0 on 2021-12-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_alter_teacher_lesson_name_delete_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lesson_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lesson_num',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lesson_pdf',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_num', models.IntegerField(default=None)),
                ('lesson_name', models.CharField(max_length=255, null=True)),
                ('lesson_pdf', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('lesson_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to='faculty.teacher')),
            ],
        ),
    ]
