# Generated by Django 4.0 on 2021-12-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_remove_teacher_lesson_name_remove_teacher_lesson_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('name',)},
        ),
    ]
